import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { FormData } from '../../types/form';

const initialState: FormData = {
  companyCategory: [],
  companyName: '',
  yearEstablished: '',
  directorName: '',
  directorPhone: '',
  directorEmail: '',
  altContactName: '',
  altContactPhone: '',
  altContactEmail: '',
  websiteUrl: '',
  companyProfileLink: '',
  promoVideoFiveMinUrl: '',
  promoVideoOneMinUrl: '',
  officeAddress: '',
  city: '',
  state: '',
  country: '',
  postalCode: '',
  legalName: '',
  gstin: '',
  cinOrUdyamOrPan: '',
  supportEmail: '',
  whatsappNumber: '',
  socialLinks: {
    linkedin: '',
    facebook: '',
    instagram: '',
    youtube: '',
    twitter: '',
    website: '',
    cin: '',
    udyam: '',
    pan: '',
  },
  operatingHours: '',
  promoCode: '',
  sectorsServed: [],
  sectorsOther: '',
  mainCategories: [],
  otherMainCategories: '',
  geographyOfOperations: [],
  coverageType: '',
  manufacturingSubcategories: [],
  manufOther: '',
  dgcaTypeCertificateUrl: '',
  serviceSubcategories: [],
  servicesOther: '',
  trainingTypes: [],
  trainingOther: '',
  rptoAuthorisationCertificateUrl: '',
  photoVideoSubcategories: [],
  photoVideoOther: '',
  softwareSubcategories: [],
  softwareOther: '',
  aiSolutions: [],
  aiSolutionsOther: '',
  aiProducts: [],
  aiProductsOther: '',
  aiServices: [],
  aiServicesOther: '',
  gnssSolutions: [],
  gnssSolutionsOther: '',
  gnssProducts: [],
  gnssProductsOther: '',
  gnssServices: [],
  gnssServicesOther: '',
  heroBackgroundUrl: '',
  primaryCtaText: '',
  primaryCtaLink: '',
  secondaryCtaText: '',
  secondaryCtaLink: '',
  aboutTitle: '',
  aboutImageUrl: '',
  aboutExperienceYears: 0,
  aboutTeamExperience: '',
  companyValuesSelection: [],
  servicesTitle: '',
  servicesDescription: '',
  services: [],
  productsTitle: '',
  productCategories: '',
  products: [],
  clientsTitle: '',
  clients: [],
  testimonials: [],
  contactTitle: '',
  contactEmail: '',
  contactPhone: '',
  addressLine: '',
  pinCode: '',
  mapEmbedUrl: '',
  contactFormText: '',
  submitButtonText: '',
  footerLogoUrl: '',
  footerDescriptionDraft: '',
  footerText: '',
  footerEmail: '',
  footerPhone: '',
  footerAddress: '',
  footerNavLinks: [],
  newsletterEnabled: false,
  newsletterDescription: '',
  promoFormats: [],
  billingContactName: '',
  billingContactEmail: '',
  billingGstDetails: '',
  billingAddress: '',
  paymentMethod: '',
  acceptTerms: false,
  acceptPrivacy: false,
  companyLogoUrl: '',
  brochurePdfUrl: '',
  cataloguePdfUrl: '',
  caseStudiesUrl: '',
  brandGuidelinesUrl: '',
};

export const adminFormSlice = createSlice({
  name: 'adminForm',
  initialState,
  reducers: {
    updateFormData: (state, action: PayloadAction<Partial<FormData>>) => {
      Object.assign(state, action.payload);
    },
    resetForm: () => initialState,
  },
});

export const { updateFormData, resetForm } = adminFormSlice.actions;
export default adminFormSlice.reducer;


